version: '3.4'
services:
  web:
    image: docker.bj1580.top/exposed_app:105
    environment:
      - logbackFile=logback_prod.xml
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 2
        order: start-first
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1'
          memory: 200M
        reservations:
          cpus: '1'
          memory: 100M
    ports:
    - 81:80
