version: '3'
services:
  web:
    image: docker.bj1580.top/exposed_app:86
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1'
          memory: 200M
    ports:
    - 80:80
