version: '3'
services:
  web:
    image: docker.bj1580.top/exposed_app:94
    environment:
      - logback.configurationFile: logback_prod.xml
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '1'
          memory: 200M
    ports:
    - 81:80
