node{
	jdk = tool name: 'jdk-1.8'
	env.JAVA_HOME = "${jdk}"
	echo "jdk installation path is: ${jdk}"
	dir('exposed'){
	    stage('Preparation'){
		    git url: 'git@github.com:shenliuyang/Exposed.git',credentialsId: '2b721860-d25b-4f0f-82f4-44ec02a9f933'
	    }
		stage('Build project'){
            sh('bash ./gradlew clean build')
		}
		def customImage
        stage('Build docker image'){
            def nameOfImage = 'docker.bj1580.top/exposed_app'
            customImage = docker.build("${nameOfImage}:${env.BUILD_ID}","-t ${nameOfImage}:latest -f ./docker/app ./")
        }
		stage('Push image to Repository'){
            docker.withRegistry('https://docker.bj1580.top', 'docker.bj1580.top') {
                customImage.push()
                customImage.push('latest')
            }
        }
	}
}
